name: composer

on:
  push:
    branches: [ source ]

jobs:
  PhpUnit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: php-actions/composer@v3 # This calls "compose install" by default :|

      - name: Run unit tests
        uses: php-actions/composer@v3
        with:
          command: test
