name: yarn

on:
  push:
    branches: [ source ]

jobs:
  Checks:
    if: github.event_name != 'push'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Install dependencies
        working-directory: ./website
        run: yarn install
      - name: Test Build
        working-directory: ./website
        run: yarn build

  Release:
    if: github.event_name != 'pull_request'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Add key to allow access to repository
        env:
          SSH_AUTH_SOCK: /tmp/ssh_agent.sock
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan github.com >> ~/.ssh/known_hosts
          echo "${{ secrets.GH_PAGES_DEPLOY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          cat <<EOT >> ~/.ssh/config
          Host github.com
          HostName github.com
          IdentityFile ~/.ssh/id_rsa
          EOT

      - name: Install dependencies
        working-directory: ./website
        run: yarn install

      - name: Deploy to GitHub Pages
        working-directory: ./website
        env:
          USE_SSH: true
          GIT_USER: git
          DEPLOYMENT_BRANCH: master
          CURRENT_BRANCH: source
        run: |
          git config --global user.email "noreply@gihub.com"
          git config --global user.name "GitHub"
          yarn deploy
